/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function anim(): void;
export function calc(): void;
export function cursor(): void;
export function custom_widget(): void;
export function either(): void;
export function event_viewer(): void;
export function flex(): void;
export function game_of_life(): void;
export function hello(): void;
export function identity(): void;
export function image(): void;
export function invalidation(): void;
export function layout(): void;
export function lens(): void;
export function list(): void;
export function multiwin(): void;
export function open_save(): void;
export function panels(): void;
export function parse(): void;
export function scroll_colors(): void;
export function scroll(): void;
export function split_demo(): void;
export function styled_text(): void;
export function switches(): void;
export function timer(): void;
export function tabs(): void;
export function view_switcher(): void;
export function widget_gallery(): void;
export function text(): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0cda70b23dc60b63(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h84af7ed0c10de93e(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
